# Generated by Django 2.0.7 on 2018-08-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='child',
            new_name='childs',
        ),
    ]
